### ISSUE TITLE
在Linux系统上安装报错

### ISSUE THREAD

**Issue by Hunter-Chen** [herodotus-cloud/eurynome-cloud-ui#2]
因为部分文件名是大写的， 在Linxu里面编译的时候，脚本里的文件名是小写， 会报找不到文件的错误。

在Windows里因为忽略大小写，编译没有问题。

**Comment by herodotus-ecosystem** [comment]
没看懂，也不知道你所说的脚本是什么。感觉你问题发错地方了。
